##:kivy
<Gerenciador>:
	Login:
		name: 'g_login'
	Menu:
		name: 'g_menu'
	Pesquisar:
		name: 'g_tarefas'
	Clientes:
		name: 'g_cliente'
	UpdateClientes:
		name: 'g_update'

<Login>
	BoxLayout:
		orientation: 'vertical'
		padding: 200
		spacing: 20
		Label:
			size_hint_x: None
			width: 100
			text: 'Usuário:'
		TextInput:
			id: iptUser
			font_size: 15
			write_tab: False
			multiline: False
		Label:
			size_hint_x: None
			width: 100
			text: 'Senha:'
		TextInput:
			id: iptPass
			font_size: 15
			write_tab: False
			multiline: False
		BoxLayout:
			orientation: 'horizontal'
			Button:
				id:btnLogin
				text: 'Login'
				on_release:
					app.root.current = 'g_menu'
			Button:
				id:btnCadastro
				text: 'Cadastro'

<Menu>
	BoxLayout:
		orientation: 'vertical'
		padding: 100
		spacing: 20

		Image:
			source: 'kivy.png'
			size_hint_y: None
			height: 128
			allow_stretch: True
		Button:
			text: 'Cadastro de Clientes'
			on_release: app.root.current = 'g_cliente'
		Button:
			text: 'Pesquisar'
			on_release: app.root.current = 'g_tarefas'
		Button:
			text: 'Sair'
			on_release: root.fecharBanco()

<Pesquisar>:
	BoxLayout:
		orientation: 'vertical'
		ActionBar:
			ActionView:
				ActionPrevious:
					title: 'Pesquisar'
					on_release: app.root.current = 'g_menu'
				ActionButton:
					text: 'Sair'
					on_release: app.root.get_screen('g_menu').fecharBanco()
		BoxLayout:
			size_hint_y: None
			height: 30
			TextInput:
				id: iptPesquisar
				font_size: 15
				write_tab: False
				multiline: False
			Button:
				text: 'Pesquisar'
				size_hint_x: None
				width: 100
				on_release:
					app.root.get_screen('g_tarefas').ids.box.clear_widgets()
					root.addWidget()
		BoxLayout:
			size_hint_y: None
			height: 30
			Button:
				text: 'ID'
				size_hint_x: None
				width: 50
			Button:
				text: 'Nome'
			Button:
				text: 'CPF'
			Button:
				text: 'Idade'
				size_hint_x: None
				width: 50
			Button:
				text: 'Telefone'
			Button:
				text: 'Cidade'
			Button:
				text: 'UF'
				size_hint_x: None
				width: 50
			Button:
				text: 'A'
				size_hint_x: None
				width: 35
			Button:
				text: 'X'
				size_hint_x: None
				width: 35
		ScrollView:
			id:scroll
			BoxLayout:
				id:box
				orientation: 'vertical'
				size_hint_y: None
				height: self.minimum_height
		
		
# regras kivy para a class Tarefa
<tarefa>:
	size_hint_y: None
	height: 30
	Label:
		id: labelid
		font_size: 15
		size_hint_x: None
		width: 50
	Label:
		id: labelnome
		font_size: 15
	Label:
		id: labelcpf
		font_size: 15
	Label:
		id: labelidade
		font_size: 15
		size_hint_x: None
		width: 50
	Label:
		id: labeltelefone
		font_size: 15
	Label:
		id: labelcidade
		font_size: 15
	Label:
		id: labeluf
		font_size: 15
		size_hint_x: None
		width: 50
	Button:
		text: 'A'
		size_hint_x: None
		width: 35
		on_release: 
			app.root.current = 'g_update'
			app.root.get_screen('g_update').telaCliente(labelid.text)
	Button:
		text: 'X'
		size_hint_x: None
		width: 35
		# app faz referência ao aplicativo que está em funcionamento
		# root é um método que faz referência a um widget mais próximo
		# (Tarefa -> BoxLayout)
		on_release: 
			app.root.get_screen('g_tarefas').ids.box.remove_widget(root)
			root.delCliente()



<Clientes>:
	BoxLayout:
		orientation: 'vertical'
		ActionBar:
			ActionView:
				ActionPrevious:
					title: 'Cadastro de Clientes'
					on_release: app.root.current = 'g_menu'
				ActionButton:
					text: 'Sair'
					on_release: app.root.get_screen('g_menu').fecharBanco()
		
		# início do formulário
		ScrollView:
			BoxLayout:
				id:box
				orientation: 'vertical'
				size_hint_y: None
				height: self.minimum_height
				padding: 10
				spacing: 10

				# formulário
				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblNome
						text: 'Nome'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptNome
						font_size: 30
						write_tab: False
						multiline: False
				
				BoxLayout:	
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblIdade
						text: 'Idade'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptIdade
						font_size: 30
						write_tab: False
						multiline: False

				
				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblCPF
						text: 'CPF'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptCPF
						font_size: 30
						write_tab: False
						multiline: False
				
				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblTelefone
						text: 'Telefone'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptTelefone
						font_size: 30
						write_tab: False
						multiline: False

				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblCidade
						text: 'Cidade'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptCidade
						font_size: 30
						write_tab: False
						multiline: False
					Label:
						id: lblUF
						text: 'UF'
						size_hint_x: None
						width: 100
					TextInput:
						id: iptUF
						font_size: 30
						write_tab: False
						multiline: False
						size_hint_x: None
						width: 150

				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblData
						text: 'Data de cadastro'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptData
						font_size: 30
						write_tab: False
						multiline: False
		BoxLayout:
			orientation: 'horizontal'
			size_hint_y: None
			height: 60
			Button:
				text: 'Salvar + '
				on_release:
					root.addCliente()
			Button:
				text: 'Salvar e Sair'
				on_release:
					root.addCliente()
					app.root.current = 'g_menu'
			

<UpdateClientes>:
	BoxLayout:
		orientation: 'vertical'
		ActionBar:
			ActionView:
				ActionPrevious:
					title: 'Alteração de Registros'
					on_release: app.root.current = 'g_menu'
				ActionButton:
					text: 'Sair'
					on_release: app.root.get_screen('g_menu').fecharBanco()
		
		# início do formulário
		ScrollView:
			BoxLayout:
				id:box
				orientation: 'vertical'
				size_hint_y: None
				height: self.minimum_height
				padding: 10
				spacing: 10

				# formulário
				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblNome
						text: 'Nome'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptNome
						font_size: 30
						write_tab: False
						multiline: False
				
				BoxLayout:	
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblIdade
						text: 'Idade'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptIdade
						font_size: 30
						write_tab: False
						multiline: False

				
				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblCPF
						text: 'CPF'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptCPF
						font_size: 30
						write_tab: False
						multiline: False
				
				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblTelefone
						text: 'Telefone'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptTelefone
						font_size: 30
						write_tab: False
						multiline: False

				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblCidade
						text: 'Cidade'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptCidade
						font_size: 30
						write_tab: False
						multiline: False
					Label:
						id: lblUF
						text: 'UF'
						size_hint_x: None
						width: 100
					TextInput:
						id: iptUF
						font_size: 30
						write_tab: False
						multiline: False
						size_hint_x: None
						width: 150

				BoxLayout:
					orientation: 'horizontal'
					size_hint_y: None
					height: 60
					Label:
						id: lblData
						text: 'Data de cadastro'
						size_hint_x: None
						width: 120
					TextInput:
						id: iptData
						font_size: 30
						write_tab: False
						multiline: False
		
		# botao para incluir
		BoxLayout:
			orientation: 'horizontal'
			size_hint_y: None
			height: 60
			Button:
				id: altButton
				text: 'Alterar'
				on_release:
					root.updateCliente()
					app.root.current = 'g_menu'
			

